#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const TJS = require('typescript-json-schema');

const generateSchema = async () => {
  const shemaTypeFilename = path.resolve(process.cwd(), 'src', 'schema', 'ConfigSchema.ts');
  const autogeneratedShemaFilename = path.resolve(
    process.cwd(),
    'src',
    'schema',
    'autogeneratedSchema.json'
  );

  if (fs.existsSync(autogeneratedShemaFilename)) {
    console.log('generate-schema: remove previous schema');
    await fs.promises.unlink(autogeneratedShemaFilename);
  }

  const settings = {
    ref: false,
    required: true,
    noExtraProps: true,
    validationKeywords: ['title', 'patternProperties', 'if', 'then', 'else'],
  };

  const program = TJS.programFromConfig('tsconfig.schema.json', [shemaTypeFilename]);

  console.log('generate-schema: start generate new schema');
  const schema = TJS.generateSchema(program, 'ConfigSchema', settings);

  await fs.promises.writeFile(
    path.resolve(autogeneratedShemaFilename),
    JSON.stringify(schema, null, 2).replace(/%40/g, '@'),
    'utf-8'
  );
  console.log('generate-schema: new schema has written successfully');
};

const generatePublicSchema = async () => {
  console.log('generate-schema: start generate new public schema');

  const topLevelSchemaFilename = path.resolve(process.cwd(), 'src', 'schema', 'topLevelSchema.js');
  const autogeneratedShemaFilename = path.resolve(
    process.cwd(),
    'src',
    'schema',
    'autogeneratedSchema.json'
  );
  const autogeneratedPublicShemaFilename = path.resolve(process.cwd(), 'schema.json');
  const topLevelSchema = require(topLevelSchemaFilename);
  const autogeneratedSchema = require(autogeneratedShemaFilename);
  const schema = topLevelSchema(autogeneratedSchema);

  if (fs.existsSync(autogeneratedPublicShemaFilename)) {
    console.log('generate-schema: remove previous public schema');
    await fs.promises.unlink(autogeneratedPublicShemaFilename);
  }

  fs.promises.writeFile(
    path.resolve(autogeneratedPublicShemaFilename),
    JSON.stringify(schema, null, 2),
    'utf-8'
  );
  console.log('generate-schema: new public schema has written successfully');
};

const main = async () => {
  await generateSchema();
  await generatePublicSchema();
};

main();
