const divider = {
  type: 'html',
  value: '<span class="sidebar-divider" />',
};

const createSidebarTitle = (title) => ({
  type: 'html',
  className: 'sidebar-title',
  value: title,
  defaultStyle: true,
});

module.exports = {
  sidebar: [
    {
      type: 'category',
      label: 'Get Started',
      items: [
        {
          type: 'autogenerated',
          dirName: '01-get-started',
        },
      ],
    },
    divider,
    {
      type: 'category',
      label: 'Tutorial',
      items: [
        {
          type: 'autogenerated',
          dirName: '02-tutorial',
        },
      ],
    },
    divider,
    createSidebarTitle('Features'),
    {
      type: 'autogenerated',
      dirName: '03-features',
    },
    divider,
    {
      type: 'category',
      label: 'Concepts',
      items: [
        {
          dirName: 'concepts',
          type: 'autogenerated',
        },
      ],
    },
    // @TODO: update docs and autogenerate all category
    {
      type: 'category',
      label: 'Features',
      items: [
        {
          type: 'ref',
          label: 'Working with React',
          id: 'references/tramvai/react',
        },
        {
          type: 'category',
          label: 'Routing',
          items: [
            {
              dirName: 'features/routing',
              type: 'autogenerated',
            },
          ],
        },
        'features/migration',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          dirName: 'guides',
          type: 'autogenerated',
        },
      ],
    },
    {
      type: 'category',
      label: 'How-to',
      items: [
        {
          dirName: 'how-to',
          type: 'autogenerated',
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        {
          dirName: 'references',
          type: 'autogenerated',
        },
      ],
    },
    {
      type: 'category',
      label: 'Releases',
      items: [
        {
          dirName: 'releases',
          type: 'autogenerated',
        },
      ],
    },
    {
      type: 'category',
      label: 'Contribute',
      items: [
        {
          dirName: 'contribute',
          type: 'autogenerated',
        },
      ],
    },
    {
      type: 'category',
      label: 'Known errors',
      items: [
        {
          dirName: 'mistakes',
          type: 'autogenerated',
        },
      ],
    },
  ],
};
