const divider = {
  type: 'html',
  value: '<span class="sidebar-divider" />',
};

const createSidebarTitle = (title) => ({
  type: 'html',
  className: 'sidebar-title',
  value: title,
  defaultStyle: true,
});

module.exports = {
  sidebar: [
    {
      type: 'category',
      label: 'Get Started',
      items: [
        {
          type: 'autogenerated',
          dirName: '01-get-started',
        },
      ],
    },
    divider,
    {
      type: 'category',
      label: 'Tutorial',
      items: [
        {
          type: 'autogenerated',
          dirName: '02-tutorial',
        },
      ],
    },
    divider,
    createSidebarTitle('Features'),
    {
      type: 'autogenerated',
      dirName: '03-features',
    },
    divider,
    {
      type: 'category',
      label: 'Concepts',
      items: [
        {
          dirName: 'concepts',
          type: 'autogenerated',
        },
      ],
    },
    // @TODO: update docs and autogenerate all category
    {
      type: 'category',
      label: 'Features',
      items: [
        {
          type: 'ref',
          label: 'Working with React',
          id: 'references/tramvai/react',
        },
        {
          type: 'category',
          label: 'Routing',
          items: [
            {
              dirName: 'features/routing',
              type: 'autogenerated',
            },
          ],
        },
        {
          type: 'category',
          label: 'State management',
          items: [
            {
              dirName: 'references/tramvai/state',
              type: 'autogenerated',
            },
          ],
        },
        {
          type: 'category',
          label: 'Data fetching',
          items: [
            {
              type: 'ref',
              label: 'HTTP requests',
              id: 'references/modules/http-client',
            },
            {
              type: 'ref',
              label: 'Available API clients',
              id: 'references/tinkoff-modules/api-clients',
            },
            {
              type: 'ref',
              label: 'Introduction to actions',
              id: 'concepts/action',
            },
            {
              type: 'ref',
              label: 'Create action',
              id: 'how-to/how-create-action',
            },
            {
              type: 'ref',
              label: 'Global actions',
              id: 'how-to/actions-execution',
            },
            {
              type: 'ref',
              label: 'Actions execution conditions',
              id: 'how-to/actions-conditions',
            },
          ],
        },
        {
          type: 'category',
          label: 'API routes',
          items: [
            'features/papi/introduction',
            {
              type: 'ref',
              label: 'Recipes',
              id: 'how-to/how-create-papi',
            },
            {
              type: 'ref',
              label: 'Library @tramvai/papi',
              id: 'references/tramvai/papi',
            },
          ],
        },
        {
          type: 'category',
          label: 'React Query',
          items: [
            {
              type: 'ref',
              label: 'API',
              id: 'references/tramvai/react-query',
            },
            {
              type: 'ref',
              label: 'Reciepes',
              id: 'how-to/react-query-usage',
            },
            {
              type: 'ref',
              label: 'Tramvai integration',
              id: 'references/modules/react-query',
            },
          ],
        },
        'features/migration',
        {
          type: 'category',
          label: 'Child App',
          items: [
            'features/child-app/overview',
            {
              type: 'ref',
              label: 'How to create Child App?',
              id: 'how-to/how-create-child-app',
            },
            {
              type: 'ref',
              label: 'Module to connect Child App',
              id: 'references/modules/child-app',
            },
            {
              type: 'ref',
              label: 'Test Child App',
              id: 'references/tramvai/test/child-app',
            },
            {
              type: 'ref',
              label: 'Интеграция с админкой',
              id: 'references/tinkoff-modules/child-app',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          dirName: 'guides',
          type: 'autogenerated',
        },
      ],
    },
    {
      type: 'category',
      label: 'How-to',
      items: [
        {
          dirName: 'how-to',
          type: 'autogenerated',
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        {
          dirName: 'references',
          type: 'autogenerated',
        },
      ],
    },
    {
      type: 'category',
      label: 'Releases',
      items: [
        {
          dirName: 'releases',
          type: 'autogenerated',
        },
      ],
    },
    {
      type: 'category',
      label: 'Contribute',
      items: [
        {
          dirName: 'contribute',
          type: 'autogenerated',
        },
      ],
    },
    {
      type: 'category',
      label: 'Known errors',
      items: [
        {
          dirName: 'mistakes',
          type: 'autogenerated',
        },
      ],
    },
  ],
};
